# Generated by Django 2.0.1 on 2019-06-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/default.jpg', max_length=200, upload_to='image/%Y/%m', verbose_name='用户贴图'),
        ),
    ]
